version: '3.8'

services:
  db:
    image: mysql/mysql-server:8.0
    platform: linux/arm64/v8
    container_name: eleave_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: eleaveup
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    container_name: eleave_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: eleave_phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - db
    restart: always

volumes:
  db_data:
