version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: eleave_db_mysql
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: eleaveup
      MYSQL_USER: admin_eleave
      MYSQL_PASSWORD: admin231
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    container_name: eleave_web
    platform: linux/amd64
    build:
      context: .
    restart: always
    ports:
      - '4000:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: eleave_phpmyadmin
    platform: linux/amd64
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '4001:80'
    depends_on:
      - db

volumes:
  db_data:
